// WordPress webpack config.
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );

// Plugins.
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );

// Utilities.
const path = require( 'path' );

// Add any new entry points by extending the webpack config.
module.exports = {
	...defaultConfig,
	...{
		entry: {
			// JavaScript files
			'js/editor': path.resolve( process.cwd(), 'resources/js', 'editor.js' ),
			'js/theme': path.resolve( process.cwd(), 'resources/js', 'theme.js' ),
			'js/admin': path.resolve( process.cwd(), 'resources/js', 'admin.js' ),

			// CSS files
			'css/theme': path.resolve( process.cwd(), 'resources/scss', 'theme.scss' ),
			'css/editor': path.resolve( process.cwd(), 'resources/scss', 'editor.scss' ),
			'css/admin': path.resolve( process.cwd(), 'resources/scss', 'admin.scss' ),
			'css/tour-operator': path.resolve( process.cwd(), 'resources/scss', 'tour-operator.scss' ),
			'css/blocks': path.resolve( process.cwd(), 'resources/scss', 'blocks.scss' ),
		},
		plugins: [
			// Include WP's plugin config.
			...defaultConfig.plugins,

			// Removes the empty `.js` files generated by webpack but
			// sets it after WP has generated its `*.asset.php` file.
			new RemoveEmptyScriptsPlugin( {
				stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS
			} )
		],
		// Customize output for theme structure
		output: {
			...defaultConfig.output,
			path: path.resolve( process.cwd(), 'public' ),
		},
	}
};
