name: Deploy Theme

on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build production assets
        run: npm run build
        
      - name: Create deployment package
        run: |
          # Create zip file excluding development files
          zip -r to-starter-theme.zip . \
            -x "node_modules/*" \
            -x "resources/*" \
            -x "tests/*" \
            -x ".github/*" \
            -x ".*" \
            -x "*.config.js" \
            -x "package*.json" \
            -x "composer.*" \
            -x "phpcs.xml"
            
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./to-starter-theme.zip
          asset_name: to-starter-theme.zip
          asset_content_type: application/zip